version: '3'

networks:
  mysql-network:
  #  postgres-network:
  redis-network:

services:
  web:
    build: ./docker
    working_dir: /var/www
    restart: always
    networks:
      - mysql-network
      # - redis-network
      # - postgres-network
    depends_on:
      - mysql
      # - postgres
      # - redis
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '.:/var/www'
      - './docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf'
      - './docker/apache/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf'
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - DOCUMENT_ROOT=/var/www/public_html
      - APACHE_LOG_DIR=/var/www/docker/apache/logs

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    networks:
      - mysql-network
    ports:
      - '3306:3306'
    volumes:
      - './docker/mysql/config:/etc/mysql/conf.d'
      - './docker/mysql/database:/var/lib/mysql'
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development

  #  phpmyadmin:
  #    image: phpmyadmin/phpmyadmin
  #    container_name: phpmyadmin
  #    networks:
  #      - mysql-network
  #    depends_on:
  #      - mysql
  #    environment:
  #      PMA_HOST: mysql
  #      PMA_PORT: 3306
  #    ports:
  #      - '8080:80'

  #  postgres:
  #    image: postgres
  #    restart: always
  #    container_name: postgres
  #    networks:
  #      - postgres-network
  #    ports:
  #      - '5432:5432'
  #    volumes:
  #      - './docker/postgres:/var/lib/postgresql/data'
  #    environment:
  #      - POSTGRES_USER=root
  #      - POSTGRES_PASSWORD=root
  #      - POSTGRES_DB=development

  #  redis:
  #    image: bitnami/redis:latest
  #    restart: always
  #    container_name: redis
  #    volumes:
  #      - ./docker/redis:/bitnami/redis/data
  #    networks:
  #      - redis-network
  #    environment:
  #      - ALLOW_EMPTY_PASSWORD=no
  #      - REDIS_PASSWORD=${REDIS_PASSWORD:-docker}
  #    ports:
  #      - '6379:6379'
